name: Firebase Continuous Deployment

on:
  push:
    branches: [ master ]

env:
  WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
  STRAVA_REFRESH: ${{ secrets.STRAVA_REFRESH }}
  STRAVA_ID: ${{ secrets.STRAVA_ID }}
  STRAVA_SECRET: ${{ secrets.STRAVA_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm ci
      - name: Github Action for Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          FOLDER: out
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
