name: Firebase Continuous Deployment

on:
  push:
    branches: [ master ]

env:
  envkey_WEATHER_KEY: ${{ secrets.WEATHER_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm ci
        env:
          envkey_WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
      - run: npm run build
        env:
          envkey_WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
      - name: Github Action for Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          envkey_WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
